# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  major: 0
  # define minor as a counter with the prefix as variable major, and seed as 100.
  minor: 10
  combinedMajorMinor: "${{variables['major']}}.${{variables['minor']}}"
  patch: "$[counter(variables['combinedMajorMinor'], 1)]"

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release -p:Version=${{variables.major}}.${{variables.minor}}.${{variables.patch}}'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'